name: pest Continuous Integration

on:
  push:
    branches:
      - staging
      - trying
      - master
  pull_request:
    branches:
      - staging
      - trying
      - master
  release:
    types: [published]

jobs:
  testing:
    name: Unit, Style, and Lint Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Install Rust Stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.51.0 # Pinned warnings
          components: rustfmt, clippy
          default: true
      - name: Install gcc
        run: sudo apt-get update && sudo apt-get install -y gcc
      - name: Bootstraping Grammars - Building
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --package pest_bootstrap
      - name: Bootstraping Grammars - Executing
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: --package pest_bootstrap
      - name: Cargo Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all --verbose
      - name: Cargo Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all --verbose
      - name: Cargo Doc
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --all --verbose
      - name: Cargo Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all -- -D warnings
      - name: Cargo Fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
            
  publish:
    # Only do this job if publishing a release
    if: github.event_name == 'release' && github.event.action == 'published'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Verify tag version
        run: |
          cargo install toml-cli
          ./.github/workflows/scripts/verify_tag.sh ${{ github.ref_name }} pest/Cargo.toml
      - name: Publish crate
        uses: katyo/publish-crates@v1
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
